# Generated by Django 3.2.13 on 2022-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustriaPyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreindustria', models.CharField(max_length=50)),
                ('descripcionindustria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'IndustriaPyme',
                'verbose_name_plural': 'IndustriaPyme',
            },
        ),
    ]
