# Generated by Django 3.2.13 on 2022-05-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pyme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDemandaOferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'CategoriaDemandaOferta',
                'verbose_name_plural': 'CategoriaDemandaOferta',
            },
        ),
    ]
