# Generated by Django 3.2.13 on 2022-05-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categoriademandaoferta_nombrecategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaPyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('idcategoriademaandaoferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriademandaoferta')),
                ('idpymed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pyme')),
            ],
            options={
                'verbose_name': 'DemandaPyme',
                'verbose_name_plural': 'DemandaPyme',
            },
        ),
    ]
