# Generated by Django 3.2.13 on 2022-05-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_demandapyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriademandaoferta',
            name='nombrecategoria',
            field=models.CharField(max_length=30),
        ),
    ]
