# Generated by Django 3.2.13 on 2022-05-03 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220503_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaPyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('idcategoriademandaoferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriademandaoferta')),
                ('idpymeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pyme')),
                ('ofertapyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertaspyme', to='core.categoriademandaoferta', to_field='nombrecategoria')),
            ],
        ),
    ]
